### ISSUE TITLE
scaffolding for move images

### ISSUE THREAD

**Issue by yithian** [dustup/dustup#41]
we can probably just grab the images from dustloop's wiki.

we should think about how to store these images, especially with regards to repo size. git isn't particularly useful for blobs...

**Comment by yithian** [comment]
We also need to come up with a method for indexing images. I can think of two off the top of my head:

1. Name the image after the move (ie: `5A.svg`, `Black Oribter.png`, etc) and automatically display the image if it exists. This would be very error prone and annoying for moves with longer names.

2. Update the schema to expect an image name as part of the move. This would require more work in the movespecs, significantly so for what would otherwise be simple moves.

Am I overlooking anything? Any better ideas?

**Comment by komidore64** [comment]
Best I can come up with is referecing moves by their name (if they have one) adding a move `id` for anything that has spaces or weird characters in it, then falling back to the first input in the move's `inputs` array.

Take Carmine's `Spin! (air)` for example.

```
...
      {
        "name": "Spin! (air)",
        "id": "spin_air",
        "inputs": [
          "j.236A",
          "j.236B",
          "j.236C"
        ]
      },
...
```

That `id` could then be mapped in UNIST's `index.js`.

```
...
  images: {
    logo: require('./images/UNIST-logo.png'),
    carmine: {
      "spin_air": require('./images/carmine/spin_air.png')
    }
  }
...
```

**Comment by komidore64** [comment]
We should probably have a character `id` also if we're going to go that route. Characters may have spaces or other weird text characters in their names.

**Comment by komidore64** [comment]
I do like your idea of referencing the image in the movespec, but maybe just an ID as opposed to the filepath?

I am thinking of redoing the structure of the `data` directory a bit so that each game's `index.js` can just require a single string per character as opposed to doing the movespecs and the images separately. The latter seems a bit redundant to me.

**Comment by yithian** [comment]
I don't object to using an ID for image references.

I'm guessing that would take the shape of an `index.js` in the character's image directory, loading them up into a hash or something? I'm probably misunderstanding what you meant, though.

**Comment by yithian** [comment]
Oh, you had an example above. I'm smart!

**Comment by yithian** [comment]
I'm not sure how I feel about having the image IDs set up in `data/games/whatever/index.js`. It feels weird that we'd be defining character-specific IDs (and image paths) in there instead of in a character-specific file, if that makes sense.

What do you think about something like this:

`data/games/under_night_in_birth_exe_late_st/index.js`
```js
...
   images: {
     logo: require('./images/UNIST-logo.png')
    carmine: require('./images/carmine/index.js')
   }
...
```

`data/games/under_night_in_birth_exe_late_st/images/carmine/index.json`
```js
...
spin_air = require('./images/carmine/spin_air.png');
...
```

That could keep the game's index.js cleaner and isolate character image datastructures from each other and we'd still be able to reference the images via `game.images.carmine.spin_air` or whatever.

**Comment by yithian** [comment]
This issue will be primarily about getting the data structures in place. Pulling the actual images and committing them via git-annex will be a different issue.
