### ISSUE TITLE
standardize on an autocombo format

### ISSUE THREAD

**Issue by yithian** [dustup/dustup#61]
It looks like we have two formats for autocombo/smartsteer notation at the moment.

Some places (eg: Linne) we have complex moves with followups and others (eg: Enkidu) we just have simple moves with the repeated buttons (ie: 5CCC).

We should have a consistent format because inconsistency is bad :(

**Comment by komidore64** [comment]
I like consistency. Granted I was just copying what was on Mizuumi's wiki. Whatever we should decide (even if we have to fire up the game to check) is commit those changes back up the chain like good open-source projects.

**Comment by komidore64** [comment]
If the leading move and the follow up are both simply `5X` (basically an auto-combo), then use the shortcut style [1]. Otherwise use long form [2]

[1]
```
5CC
```

[2]
```
{
  "name": "my super awesome move",
  "inputs": [
    "236A"
  ],
  "followUps: [
    {
      "name": "my super awesome follow up",
      "inputs": [
        "236A"
      ]
    }
  ]
```

**Comment by yithian** [comment]
:+1: 

Keeps things simple for autocombos but special chains/rekkas/etc keep their specialness.

**Comment by komidore64** [comment]
I will look into seeing if we can do this with the movespec schema.

**Comment by komidore64** [comment]
Using regexs for inputs is broken by Yuzuriha from UNIST. I'm not sure if programmatically validating numpad notation is possible if we need to put sentences in there?

**Comment by yithian** [comment]
What are you trying to validate on the input?

**Comment by komidore64** [comment]
Just to make sure it's valid numpad and not gobbledigook

**Comment by komidore64** [comment]
And that autocombo shortcuts are the only things that have multi-action button presses in them

**Comment by komidore64** [comment]
Maybe that's overkill though
