### ISSUE TITLE
Set "Guard Thrust" instead of "Guard Cancel"

### ISSUE THREAD

**Issue by komidore64** [dustup/dustup#74]
Mizuumi shows `Guard Cancel` on a lot of UNIST characters when it should say `Guard Thrust`.

@yithian brought this to my attention in #73.

We should be good FGC members and submit changes to Mizuumi.

**Comment by yithian** [comment]
I'm requested an account on Mizuumi's wiki to fix this

**Comment by yithian** [comment]
mizuumi is updated
